# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Display structure of downloaded files
      run: ls -al target/Webstack-Guns-nkt-1.0.jar

    - name: 'Tar files'
      run: tar -cvf my_files.tar.gz target/Webstack-Guns-nkt-1.0.jar

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: my_files.tar.gz  
